### ISSUE TITLE
Trying Jupyter

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/book#2] opened 2016-12-16 06:39 UTC
@Zrachel reminded me few days ago that Jupyter might already fit all what we want. Andrew Ng showed me today the Google Trends of Jupyter and Zeppelin notebooks:

<img width="987" alt="screen shot 2016-12-15 at 10 03 39 pm" src="https://cloud.githubusercontent.com/assets/1548775/21254019/6e68c492-c317-11e6-95d1-670f16c29f3f.png">

So I think I need to try Jupyter at least on my laptop.

**Comment by wangkuiyi** [comment] 2016-12-16 06:42
Here follows how I install Jupyter on my MacBook Pro:

1. Install Python3 and pip3:

   ```
   brew update && brew install python3
   curl https://bootstrap.pypa.io/get-pip.py | python3
   pip3 install --upgrade pip
   ```

1. Install Jupyter using pip3

   ```
   pip3 install jupyter
   ```

1. Start Jupyter server

   ```
   jupyter notebook
   ```

   This also opens a Web browser window and the Web page shows the current directory. I can select and edit files.

**Comment by Zrachel** [comment] 2016-12-16 06:53
Yes, ipython notebook is a wonderful tool in writing markdown docs while executing python scripts. However, we need paddle train python interface.

PS: Xiao Wang once reminded us the difference between zepplin ipython notebook: 
https://www.opendatascience.com/blog/jupyter-zeppelin-beaker-the-rise-of-the-notebooks/

**Comment by wangkuiyi** [comment] 2016-12-16 07:12
@Zrachel I learned how to create a .ipynb file and save it as Markdown file. But I didn't find a way to loading a notebook from a Markdown file. I'd thought that Jupyter supports two notebook file formats -- .ipynb and .md, am I wrong?

**Comment by Zrachel** [comment] 2016-12-16 07:16
@wangkuiyi To my knowledge, markdown file can be converted to ipynb by some tools (e.g https://github.com/aaren/notedown), but I have not use this. But ipynb can be easily converted by markdown.

**Comment by wangkuiyi** [comment] 2016-12-16 19:01
I got it. Thanks! @Zrachel

**Comment by shanyi15** [comment] 2018-08-15 09:18
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:18 UTC
