### ISSUE TITLE
Cut a release branch for v2. 

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/book#527] opened 2018-05-31 18:53 UTC
As Paddle moving forward, `book` should also update its tutorial examples. We certainly want to keep the old example around as references. 

Therefore, we should cut a release version `release/0.10.0` now to indicate that all the existing example will work with `paddle 0.10.0`

Once the release branch is cut, we can freely update the example in `develop` with the fluid contents. This allows us to focus with the latest paddle fluid example and no long need to worry about v2 example. Of course, we still have the ability to update `v2` examples if necessary. If we need to update any `v2` example, we can still go back to the `release/0.10.0` branch to update the documentation.

**Comment by shanyi15** [comment] 2018-08-15 09:07
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:07 UTC
