### ISSUE TITLE
太难用了，文档说明和程序实现都不一致

### ISSUE THREAD

**Issue by liuchyi** [PaddlePaddle/book#449] opened 2017-11-21 12:27 UTC
![image](https://user-images.githubusercontent.com/6964441/33072312-edfb6b30-cef9-11e7-944d-017567fd8f70.png)
文档中说明可以不用传入字典文件和标签字典，但实现却又是另一回事，这个也算了，字典文件是怎样格式，标签字典又是怎样的，也没有说明，能不能走心一点，不是每个人都是大神，我们只是一个想进门的小白，请paddlepaddle不要再标榜简单易用了，好么？
![image](https://user-images.githubusercontent.com/6964441/33072357-22dcf468-cefa-11e7-9812-4e5935953222.png)

**Comment by liuchyi** [comment] 2017-11-21 12:30
文本分类的例子

**Comment by shanyi15** [comment] 2018-08-15 09:08
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:08 UTC
