### ISSUE TITLE
DSSM训练不收敛

### ISSUE THREAD

**Issue by chengxiaohua1105** [PaddlePaddle/book#516] opened 2018-05-03 06:16 UTC
models里面的DSSM模型训练不收敛，请问是否有案例成功将models里面的DSSM模型训练收敛？

**Comment by JiayiFeng** [comment] 2018-05-04 02:45
测试了一下可以正常收敛：
命令：
```
python train.py -y 0 --model_arch 0 --class_num 2
```

结果：
```
[INFO 2018-05-04 02:43:53,301 utils.py:125] The arguments passed by command line is :
[INFO 2018-05-04 02:43:53,302 utils.py:127] batch_size:	32
[INFO 2018-05-04 02:43:53,302 utils.py:127] class_num:	2
[INFO 2018-05-04 02:43:53,302 utils.py:127] dnn_dims:	256,128,64,32
[INFO 2018-05-04 02:43:53,302 utils.py:127] model_arch:	fc
[INFO 2018-05-04 02:43:53,302 utils.py:127] model_output_prefix:	./
[INFO 2018-05-04 02:43:53,303 utils.py:127] model_type:	classification
[INFO 2018-05-04 02:43:53,303 utils.py:127] num_batches_to_log:	100
[INFO 2018-05-04 02:43:53,303 utils.py:127] num_batches_to_save_model:	400
[INFO 2018-05-04 02:43:53,303 utils.py:127] num_batches_to_test:	200
[INFO 2018-05-04 02:43:53,303 utils.py:127] num_passes:	10
[INFO 2018-05-04 02:43:53,303 utils.py:127] num_workers:	1
[INFO 2018-05-04 02:43:53,303 utils.py:127] share_embed:	False
[INFO 2018-05-04 02:43:53,304 utils.py:127] share_network_between_source_target:	False
[INFO 2018-05-04 02:43:53,304 utils.py:127] source_dic_path:	None
[INFO 2018-05-04 02:43:53,304 utils.py:127] target_dic_path:	None
[INFO 2018-05-04 02:43:53,304 utils.py:127] test_data_path:	None
[INFO 2018-05-04 02:43:53,304 utils.py:127] train_data_path:	None
[INFO 2018-05-04 02:43:53,304 utils.py:127] use_gpu:	False
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
I0504 02:43:53.403563  1063 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1
[WARNING 2018-05-04 02:43:53,406 network_conf.py:53] Build DSSM model with config of classification, fc
[INFO 2018-05-04 02:43:53,407 network_conf.py:54] The vocabulary size is : [10, 10]
('model type: ', 'classification')
[INFO 2018-05-04 02:43:53,407 network_conf.py:174] build classification model
[INFO 2018-05-04 02:43:53,409 network_conf.py:87] Create embedding table [source] whose dimention is 256.
[INFO 2018-05-04 02:43:53,410 network_conf.py:87] Create embedding table [target] whose dimention is 256.
[INFO 2018-05-04 02:43:53,412 network_conf.py:163] create fc layer [source_fc_0_128] which dimention is 128
[INFO 2018-05-04 02:43:53,413 network_conf.py:163] create fc layer [source_fc_1_64] which dimention is 64
[INFO 2018-05-04 02:43:53,414 network_conf.py:163] create fc layer [source_fc_2_32] which dimention is 32
[INFO 2018-05-04 02:43:53,417 network_conf.py:163] create fc layer [target_fc_0_128] which dimention is 128
[INFO 2018-05-04 02:43:53,418 network_conf.py:163] create fc layer [target_fc_1_64] which dimention is 64
[INFO 2018-05-04 02:43:53,419 network_conf.py:163] create fc layer [target_fc_2_32] which dimention is 32
I0504 02:43:53.430722  1063 GradientMachine.cpp:94] Initing parameters..
I0504 02:43:53.439846  1063 GradientMachine.cpp:101] Init parameters done.
[INFO 2018-05-04 02:43:53,623 reader.py:31] [reader] load trainset from ./data/classification/train.txt
[INFO 2018-05-04 02:43:53,896 train.py:231] Pass 0, Batch 0, Cost 0.797559, {'__auc_evaluator_0__': 0.0, 'classification_error_evaluator': 0.5}
[INFO 2018-05-04 02:43:53,971 reader.py:31] [reader] load trainset from ./data/classification/train.txt
[INFO 2018-05-04 02:43:54,106 train.py:231] Pass 1, Batch 0, Cost 0.647858, {'__auc_evaluator_0__': 1.0, 'classification_error_evaluator': 0.5}
[INFO 2018-05-04 02:43:54,180 reader.py:31] [reader] load trainset from ./data/classification/train.txt
[INFO 2018-05-04 02:43:54,315 train.py:231] Pass 2, Batch 0, Cost 0.522541, {'__auc_evaluator_0__': 1.0, 'classification_error_evaluator': 0.0}
[INFO 2018-05-04 02:43:54,388 reader.py:31] [reader] load trainset from ./data/classification/train.txt
[INFO 2018-05-04 02:43:54,499 train.py:231] Pass 3, Batch 0, Cost 0.420472, {'__auc_evaluator_0__': 1.0, 'classification_error_evaluator': 0.0}
[INFO 2018-05-04 02:43:54,564 reader.py:31] [reader] load trainset from ./data/classification/train.txt
[INFO 2018-05-04 02:43:54,672 train.py:231] Pass 4, Batch 0, Cost 0.338234, {'__auc_evaluator_0__': 1.0, 'classification_error_evaluator': 0.0}
[INFO 2018-05-04 02:43:54,738 reader.py:31] [reader] load trainset from ./data/classification/train.txt
[INFO 2018-05-04 02:43:54,848 train.py:231] Pass 5, Batch 0, Cost 0.272065, {'__auc_evaluator_0__': 1.0, 'classification_error_evaluator': 0.0}
[INFO 2018-05-04 02:43:54,914 reader.py:31] [reader] load trainset from ./data/classification/train.txt
[INFO 2018-05-04 02:43:55,023 train.py:231] Pass 6, Batch 0, Cost 0.218897, {'__auc_evaluator_0__': 1.0, 'classification_error_evaluator': 0.0}
[INFO 2018-05-04 02:43:55,089 reader.py:31] [reader] load trainset from ./data/classification/train.txt
[INFO 2018-05-04 02:43:55,197 train.py:231] Pass 7, Batch 0, Cost 0.176410, {'__auc_evaluator_0__': 1.0, 'classification_error_evaluator': 0.0}
[INFO 2018-05-04 02:43:55,263 reader.py:31] [reader] load trainset from ./data/classification/train.txt
[INFO 2018-05-04 02:43:55,371 train.py:231] Pass 8, Batch 0, Cost 0.142733, {'__auc_evaluator_0__': 1.0, 'classification_error_evaluator': 0.0}
[INFO 2018-05-04 02:43:55,437 reader.py:31] [reader] load trainset from ./data/classification/train.txt
[INFO 2018-05-04 02:43:55,551 train.py:231] Pass 9, Batch 0, Cost 0.116238, {'__auc_evaluator_0__': 1.0, 'classification_error_evaluator': 0.0}
[INFO 2018-05-04 02:43:55,589 train.py:260] Training has finished.
```

**Comment by chengxiaohua1105** [comment] 2018-05-04 03:52
check一下models里面的测试数据，好像测试数据特别少，我自己大数据训练，并从多方了解到这个模型是收敛不了。

**Comment by shanyi15** [comment] 2018-08-15 09:07
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:07 UTC
