### ISSUE TITLE
对于ParamAttr本身，添加更多的描述说明。

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/book#275] opened 2017-04-10 08:10 UTC
主要关联的文章包括

```bash
$ grep -n 'param_attr' $(find . -name '*.md' )
```

```text
./04.word2vec/README.en.md:234:        param_attr=paddle.attr.Param(
./04.word2vec/README.en.md:281:                          param_attr=paddle.attr.Param(
./04.word2vec/README.md:219:        param_attr=paddle.attr.Param(
./04.word2vec/README.md:266:                          param_attr=paddle.attr.Param(
./05.understand_sentiment/README.en.md:224:                             param_attr=para_attr,
./05.understand_sentiment/README.en.md:242:                             param_attr=para_attr)
./05.understand_sentiment/README.md:208:                             param_attr=para_attr,
./05.understand_sentiment/README.md:224:                             param_attr=para_attr)
./06.label_semantic_roles/README.en.md:281:    param_attr=paddle.attr.Param(
./06.label_semantic_roles/README.en.md:284:    size=mark_dim, input=mark, param_attr=std_0)
./06.label_semantic_roles/README.en.md:289:        size=word_dim, input=x, param_attr=emb_para) for x in word_input
./06.label_semantic_roles/README.en.md:303:            input=emb, param_attr=std_default) for emb in emb_layers
./06.label_semantic_roles/README.en.md:317:    param_attr=lstm_para_attr)
./06.label_semantic_roles/README.en.md:328:                input=input_tmp[0], param_attr=hidden_para_attr),
./06.label_semantic_roles/README.en.md:330:                input=input_tmp[1], param_attr=lstm_para_attr)
./06.label_semantic_roles/README.en.md:340:        param_attr=lstm_para_attr)
./06.label_semantic_roles/README.en.md:353:         input=input_tmp[0], param_attr=hidden_para_attr),
./06.label_semantic_roles/README.en.md:355:         input=input_tmp[1], param_attr=lstm_para_attr)
./06.label_semantic_roles/README.en.md:366:    param_attr=paddle.attr.Param(
./06.label_semantic_roles/README.en.md:380:   param_attr=paddle.attr.Param(name='crfw'))
./06.label_semantic_roles/README.md:258:    param_attr=paddle.attr.Param(
./06.label_semantic_roles/README.md:261:    size=mark_dim, input=mark, param_attr=std_0)
./06.label_semantic_roles/README.md:266:        size=word_dim, input=x, param_attr=emb_para) for x in word_input
./06.label_semantic_roles/README.md:280:        input=emb, param_attr=std_default) for emb in emb_layers
./06.label_semantic_roles/README.md:294:    param_attr=lstm_para_attr)
./06.label_semantic_roles/README.md:305:                input=input_tmp[0], param_attr=hidden_para_attr),
./06.label_semantic_roles/README.md:307:                input=input_tmp[1], param_attr=lstm_para_attr)
./06.label_semantic_roles/README.md:317:        param_attr=lstm_para_attr)
./06.label_semantic_roles/README.md:330:        input=input_tmp[0], param_attr=hidden_para_attr),
./06.label_semantic_roles/README.md:332:        input=input_tmp[1], param_attr=lstm_para_attr)
./06.label_semantic_roles/README.md:343:    param_attr=paddle.attr.Param(
./06.label_semantic_roles/README.md:357:   param_attr=paddle.attr.Param(name='crfw'))
./07.machine_translation/README.en.md:264:        param_attr=paddle.attr.ParamAttr(name='_source_language_embedding'))
./07.machine_translation/README.en.md:357:        param_attr=paddle.attr.ParamAttr(name='_target_language_embedding'))
./07.machine_translation/README.md:228:        param_attr=paddle.attr.ParamAttr(name='_source_language_embedding'))
./07.machine_translation/README.md:319:        param_attr=paddle.attr.ParamAttr(name='_target_language_embedding'))
```

关联PR #274

**Comment by shanyi15** [comment] 2018-08-15 09:09
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:09 UTC
