### ISSUE TITLE
Accuracy goes down with higher PASS_NUM

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/book#522] opened 2018-05-22 23:08 UTC
In PaddlePaddle's book chapter (Recommendation System), I tuned the PASS_NUM to be higher [here](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/test_recommender_system.py#L218)

But the accuracy goes down... From `ml-1m` dataset, we can know the real rating from user 1 to movie 783 is 4

`1::783::4::978824291`

But the experimental result never went pass 3 ...

```python
(Pdb) np.array(user_id)[0][0]
1
(Pdb) np.array(movie_id)[0][0]
783
NUM_PASS 
100
('inferred score: ', array([[2.1509817]], dtype=float32))

500
('inferred score: ', array([[2.3413014]], dtype=float32))

5000
('inferred score: ', array([[2.3629897]], dtype=float32))

500000
('inferred score: ', array([[2.8035383]], dtype=float32))

50000000 (because it is over 1M ???)
('inferred score: ', array([[2.038723]], dtype=float32))

1000000 (1M)
('inferred score: ', array([[2.015883]], dtype=float32))

```

**Comment by shanyi15** [comment] 2018-08-15 09:07
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:07 UTC
