### ISSUE TITLE
Profiling python codes of all demos in the book

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/book#279] opened 2017-04-14 08:41 UTC
Since demos in paddle book are given for the beginners to learn deep learning with Paddle, it's import to make sure the training process is efficient. It's necessary to profile python codes of all demos in the book to find the speed bottleneck and memory usage. And an automatic profiling tool is needed to make the profiling work conveniently.

**Comment by luotao1** [comment] 2017-04-14 09:05
机器翻译示例的生成过程，初始化（从启动程序到打印出生成网络结构）需要半分钟的时间，比v1版本慢很多：
```
I0414 17:04:18.674283 20970 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
[INFO 2017-04-14 17:04:43,138 networks.py:1472] The input order is [source_language_word]
[INFO 2017-04-14 17:04:43,138 networks.py:1478] The output order is [__beam_search_predict__]
```

**Comment by shanyi15** [comment] 2018-08-15 09:09
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:09 UTC
