### ISSUE TITLE
image_classification was killed when I run the train.py in docker

### ISSUE THREAD

**Issue by KawhiZhuuu** [PaddlePaddle/book#474] opened 2017-12-25 12:01 UTC
Version: Last
Platform: macOS High Sierra 10.13.2, Docker 17.09.1-ce, paddle 0.11.0
Log:
![paddlelog](https://user-images.githubusercontent.com/16774273/34339346-ea6fab06-e9ad-11e7-9eb6-edc844150215.jpg)

Debug:
It was killed when the trainer began training.The event_handler received BeginPass status and BeginInteration status.But there were no EndIteration status or EndPass status.

**Comment by will-am** [comment] 2017-12-25 13:53
By default, the image classification example requires GPU with large memory to run. If no GPU present,  you can change the use_gpu=False in paddle.init to run this example with CPU.

**Comment by KawhiZhuuu** [comment] 2017-12-26 02:22
@will-am, it was killed again though I changed the train.py's "with_gpu" to "False".

**Comment by will-am** [comment] 2017-12-26 02:29
I am not sure, maybe the memory usage exceeds the limit of docker. I suggest directly installing paddle with `pip install paddlepaddle` and rerun the training.

**Comment by KawhiZhuuu** [comment] 2017-12-27 02:22
Emmmm...how much space is enough for this demo?

**Comment by will-am** [comment] 2017-12-27 03:06
For VGG16 net, when the batch_size is 128, it would require two GPUs, each with 12G GPU memory. When the memory is limited, you have to reduce the batch size and/or use less layers.

**Comment by shanyi15** [comment] 2018-08-15 09:08
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:08 UTC
