### ISSUE TITLE
应用模型对图片分类问题

### ISSUE THREAD

**Issue by yqxqls** [PaddlePaddle/book#360] opened 2017-08-04 01:45 UTC
请问图中的label是5，是什么意思，怎么定义的？如图
![image](https://user-images.githubusercontent.com/26181201/28950818-86e3c0ec-78f9-11e7-8de1-f01242da015b.png)

**Comment by yqxqls** [comment] 2017-08-09 01:46
为什么没有人回复的？？？

**Comment by qingqing01** [comment] 2017-08-15 02:50
@yqxqls 不好意思回复晚了。label 5是dog这一类，来自数据官网给出的定义，请参考 https://github.com/PaddlePaddle/book/issues/362 给出了详细解释。

**Comment by shanyi15** [comment] 2018-08-15 09:15
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:15 UTC
