### ISSUE TITLE
several question about book migration

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/book#464] opened 2017-12-12 03:52 UTC
- should the python syntax be exactly the same with V2 API?
  - currently, we have some new concept such as `executor`, `default_program`, `fetch_list`
  - some new concepts bring flexibility(such as `while op`) and are hard to hide as the underlying of V2 API.

- when the book based on Fluid is completed, should we discard the old V2 content?
  - during migration, new content will be placed to a `chapter_xxx_fluid` directory
  - the new Fluid content can co-exist with the V2 content.
  - if we want to drop V2 content, just replace them with `chapter_xxx_fluid`.

**Comment by kavyasrinet** [comment] 2017-12-12 04:23
In addition to the list above, we should also discuss the following/ add them to our TODO list:
1.  Have documentation for the new concepts we have introduced in `fluid` as mentioned above.
2.  The python files as of now do not have a 1:1 mapping from the `fluid/test/book` to the chapters of the book. We should re-write that part and combine different implementations if required (for example :  `recognize_digits` and `understand_sentiment`).
3.  Plot the training curves again using the `fluid` code.
4. Rewrite code snippets back to the book's markdowns.

**Comment by wanghaoshuang** [comment] 2017-12-12 04:52
> when the book based on Fluid is completed, should we discard the old V2 content?

We had better keep the V2 content accessible. By default,  we can show `chapter_xxx_fluid` in [this page](http://book.paddlepaddle.org/index.html). And  attach the hyperlink of relevant V2 content in each chapter.

**Comment by dzhwinter** [comment] 2017-12-12 14:18
Considering  V2 API released no longer than one year, it's better to keep compatible with V2 API.  We aim to deliver an industrial-grade framework, frequently changing the API will lose users confidence. 
So the question converts to **how to keep compatible with V2 API**. In Fluid, our design philosophy is totally different from previous ones, there is some fundamental concept need to expose, such as `Program`, `LoDTensor`.

1. Create A Fluid directory, put the new implementation into it. 
Because book with V2 API is a stable version, but the Fluid books are not. We still keep polishing the Fluid books, will swap the `for loop` with `while op` in next stage.

2. Add deprecated warning message to old API, and give a good suggestion in our document, then people will accept the Fluid more smoothly.

**Comment by shanyi15** [comment] 2018-08-15 09:08
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:08 UTC
Labels: migration
