### ISSUE TITLE
Jupyter kernel died

### ISSUE THREAD

**Issue by benoit-cty** [PaddlePaddle/book#248] opened 2017-03-21 12:39 UTC
Hello,

This project is really nice !

Unfortunately the Jupyter Notebook crash on the running of last cell, for the "01.fit_a_line" and "04.word2vec" notebook at least.

I was able to:
- dowload the docker image
- run it
- Access to http://localhost:8888/notebooks/04.word2vec/README.en.ipynb
- Run all cell
=> On the last cell I have a message "The kernel appears to have died. It will restart automatically."

I have access to the docker image by "sudo docker exec -i -t 45662692a6ad /bin/bash"

**But how to have some log info to know what happen ?**

My configuration is a Ubuntu 16.04 laptop, intel core i5 with 6Gb or RAM, without GPU

**Comment by NorthStar** [comment] 2017-03-21 16:53
Hi trancept,

Crashing: It is usually a memory issue, among other things, and it is likely getting fixed (duplicate #231).

Logging: Do you see errors in the terminal where you ran the notebook (where you did > docker run -d -p 8888:8888 paddlepaddle/book)? That should be where the logs are.

**Comment by benoit-cty** [comment] 2017-03-22 09:10
Hi NorthStar, thanks for helping.

The computer memory don't increase, it stay at 70%.

Here is what I saw after doing a "sudo docker attach 45662692a6ad" :
```
I0322 09:05:23.182615   184 Util.cpp:160] commandline:  --use_gpu=False --trainer_count=1 
I0322 09:06:02.912057   184 GradientMachine.cpp:86] Initing parameters..
I0322 09:06:02.949656   184 GradientMachine.cpp:93] Init parameters done.
Thread [139770985629440] Forwarding __fc_layer_0__, x, 
*** Aborted at 1490173578 (unix time) try "date -d @1490173578" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGILL (@0x7f1eddbe1522) received by PID 184 (TID 0x7f1ef7f2c700) from PID 18446744073134806306; stack trace: ***
    @     0x7f1ef76e6890 (unknown)
    @     0x7f1eddbe1522 sgemm_kernel
[I 09:06:21.817 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 40b65a78-9168-4b4c-ae93-c326cc0f1e46 restarted
[I 09:06:27.968 NotebookApp] Saving file at /01.fit_a_line/README.en.ipynb

```

**Comment by gangliao** [comment] 2017-03-22 09:16
Hi, @trancept

Can you show me the details of your physical machine?  

 ** SIGILL ** means that illegal hardware instructions being used.

You can simply issue the command: `grep avx /proc/cpuinfo` to check the machine whether supports avx instructions.

**Comment by benoit-cty** [comment] 2017-03-22 09:37
Hi Gangliao,
Here is the output:

> grep avx /proc/cpuinfo
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave **avx** lahf_lm epb tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave **avx** lahf_lm epb tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave **avx** lahf_lm epb tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave **avx** lahf_lm epb tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts
> 


`model name	: Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
stepping	: 7
microcode	: 0x29
cpu MHz		: 1197.167
cache size	: 3072 KB
`

**Comment by gangliao** [comment] 2017-03-22 09:40
That's quite strange. Did you use docker in VM?
Can you run other demos in the book?

**Comment by benoit-cty** [comment] 2017-03-22 09:56
Non, it's a native 16.04 install. It's the french version. I will try with a reboot ;-)

**Comment by benoit-cty** [comment] 2017-03-22 10:06
Same error after reboot:
Memory under 50% and CPU under 70% in peak. Running docker as root.
Is anything else I can test ?
`[I 10:03:53.531 NotebookApp] Kernel started: 355ddf25-33ed-49ed-a397-c43d10f22651
I0322 10:04:22.283298    13 Util.cpp:160] commandline:  --use_gpu=False --trainer_count=1 
I0322 10:04:23.307060    13 GradientMachine.cpp:86] Initing parameters..
I0322 10:04:23.307096    13 GradientMachine.cpp:93] Init parameters done.
Thread [139674572465920] Forwarding __fc_layer_0__, x, 
*** Aborted at 1490177067 (unix time) try "date -d @1490177067" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGILL (@0x7f08633e4522) received by PID 13 (TID 0x7f088546a700) from PID 1665025314; stack trace: ***
    @     0x7f0884c24890 (unknown)
    @     0x7f08633e4522 sgemm_kernel
[I 10:04:29.532 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 355ddf25-33ed-49ed-a397-c43d10f22651 restarted
`

**Comment by gangliao** [comment] 2017-03-22 10:09
You can test digits recognition in your docker image ...

**Comment by benoit-cty** [comment] 2017-03-22 10:16
Not better:
`I0322 10:15:09.460373    50 Util.cpp:160] commandline:  --use_gpu=False --trainer_count=1 
I0322 10:15:09.658946    50 GradientMachine.cpp:86] Initing parameters..
I0322 10:15:09.691876    50 GradientMachine.cpp:93] Init parameters done.
Thread [140154603984640] Forwarding __fc_layer_0__, pixel, 

*** Aborted at 1490177725 (unix time) try "date -d @1490177725" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGILL (@0x7f78273dd6b8) received by PID 50 (TID 0x7f7849625700) from PID 658364088; stack trace: ***
    @     0x7f7848ddf890 (unknown)
    @     0x7f78273dd6b8 sgemm_kernel


gzip: stdout: Broken pipe
[I 10:15:28.265 NotebookApp] KernelRestarter: restarting kernel (1/5)
`

**Comment by benoit-cty** [comment] 2017-03-22 10:24
My CPU support AVX but not AVX2, could it be the problem ?

**Comment by gangliao** [comment] 2017-03-22 10:31
This error throws out from OpenBlas `sgemm_kernel`, I am not sure about it either. But, it seems an OpenBlas problem. I will open a GitHub issue for them, too.  https://github.com/xianyi/OpenBLAS/issues/1134

Thanks for your feedback!

If any update, I will @ you.

**Comment by benoit-cty** [comment] 2017-03-22 12:57
I just test it on a Microsoft Azure Ubuntu 16.04 instance and it works.
It is most probably a missing instruction on my laptop.
Thanks for your help.

**Comment by shanyi15** [comment] 2018-08-15 09:10
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:10 UTC
