### ISSUE TITLE
machine_translation中案例出现Cost nan现象

### ISSUE THREAD

**Issue by zqmath1994** [PaddlePaddle/book#501] opened 2018-03-21 03:23 UTC
machine_translation中案例出现Cost nan现象，厂内0.10.0-gpu-book镜像，用nvidia-docker,版本是Docker version 1.11.2, build b9f10c9

**Comment by typhoonzero** [comment] 2018-03-21 06:06
和 @luotao1 沟通，这个issue https://github.com/PaddlePaddle/book/issues/332 已经修复了，请更新到新的版本或直接从book repo获取最新的demo代码。

**Comment by shanyi15** [comment] 2018-08-15 09:07
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:07 UTC
