### ISSUE TITLE
01.fit_a_line中的UCI Housing Data Set链接已失效

### ISSUE THREAD

**Issue by sanwushuosi** [PaddlePaddle/book#435] opened 2017-10-23 08:37 UTC
01.fit_a_line中的UCI Housing Data Set链接已失效，无法跟着教程入门

**Comment by typhoonzero** [comment] 2017-10-23 08:58
的确，我昨天也遇到了。

**Comment by sanwushuosi** [comment] 2017-10-23 09:18
不过教程里已包含数据，教程还是可以继续下去的。请忽略我第一楼的后半句。

**Comment by yeyupiaoling** [comment] 2017-10-24 13:18
好几天了，那个不过用什么用呢

**Comment by linbaicome** [comment] 2018-06-06 02:57
你是要找数据文件吗？把文件名改成.data
[housing data.txt](https://github.com/PaddlePaddle/book/files/2074631/housing.data.txt)

**Comment by shanyi15** [comment] 2018-08-15 09:17
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:17 UTC
