### ISSUE TITLE
Using trained model in Word2Vec does not give any meaningful inference

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/book#534] opened 2018-06-06 01:16 UTC
After training the word2vec model using PaddlePaddle for about 1 hour, I used it to try to predict the next word of a sentence:

`
a form of asbestos once used to make kent cigarette filters has caused a high percentage of cancer deaths among a group of workers exposed to it more than N years ago researchers reported 
`

**among a group of** is part of the sentence. But the inference gave `2072`, which is `<unk>`. Note the sentence appears exactly in the training dataset (the 5th sentence).

```python
(Pdb) word_dict['among']
211
(Pdb) word_dict['a']
6
(Pdb) word_dict['group']
96
(Pdb) word_dict['of']
4
(Pdb) first_word = fluid.create_lod_tensor([[211]], [[1]], place)
(Pdb) second_word = fluid.create_lod_tensor([[6]], [[1]], place)
(Pdb) third_word = fluid.create_lod_tensor([[96]], [[1]], place)
(Pdb) fourth_word = fluid.create_lod_tensor([[4]], [[1]], place)
(Pdb) result = inferencer.infer({'firstw': first_word,'secondw': second_word,'thirdw': third_word,'fourthw': fourth_word},return_numpy=False)
(Pdb) result_list = numpy.array(result[0])
(Pdb) np.argmax(result_list[0])
2072
(Pdb) word_dict['<unk>']
2072
```
I suspect the training data `imikolov` is not built correctly. `ptb.train.txt` file has `42068` sentences but the built `word_dict` only has 2073 words, including `a`, `the`, `<s>`, `<e>` and `<unk>`.

**Comment by daming-lu** [comment] 2018-06-06 01:25
Note that NO inference was done in previous examples:

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/test_word2vec.py#L178-L185

https://github.com/PaddlePaddle/book/blob/develop/04.word2vec/train.py#L100-L107

**Comment by shanyi15** [comment] 2018-08-15 09:07
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:07 UTC
