### ISSUE TITLE
Is there a reason for buf_size=8192 ?

### ISSUE THREAD

**Issue by alvations** [PaddlePaddle/book#333] opened 2017-06-22 08:06 UTC
For most of the demo code in the new "Deep Learning 101" book, the `buf_size=8192` is used. https://github.com/PaddlePaddle/book/search?utf8=✓&q=8192&type=

**Is there a reason for setting the value of 8192?**

**Is there a way to find out what is the maximum value we can set for the `buf_size`?**

**Comment by lcy-seso** [comment] 2017-07-15 00:41
Very sorry for such a late reply.

I am not the writer of the original codes, but I think there is no special meanings for the number 8192.

The parameter `buf_size` controls the size of a pool that training sample will first read into it after this pool is filled, then shuffle the pool and feed training samples batch by batch to Paddle trainer. The larger the `buf_size`, the better training samples shuffled. Shuffle always influences the learning performance of SGD. If I have large enough memory, I prefer a relatively large `buf_size`. But I guess the number 8192 may just be an accident, for example, the writer just copy each other's parameter setting.

**Comment by shanyi15** [comment] 2018-08-15 09:09
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:09 UTC
