### ISSUE TITLE
book示例训练完之后是没有模型和日志文件

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/book#255] opened 2017-03-26 02:39 UTC
![15b5306ba7eed5e8e51ef8a8c2f4a227](https://cloud.githubusercontent.com/assets/1908992/24327960/4f506842-1210-11e7-9668-74a13c9e3583.JPG)
如上图所示，book示例，训练完之后是没有output目录、也没找到模型和日志文件。

**Comment by llxxxll** [comment] 2017-03-28 04:13
@reyoung 求那段设置output的命令

**Comment by reyoung** [comment] 2017-04-17 06:50
@llxxxll 我会在视频录制结束之后，更新book的该章节。

**Comment by shanyi15** [comment] 2018-08-15 09:10
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:10 UTC
