### ISSUE TITLE
通过 pip 安装了 paddlepaddle 为0.10.0版本，book 中没有对应版本，经常因为版本不兼容无法运行

### ISSUE THREAD

**Issue by szxw** [PaddlePaddle/book#401] opened 2017-09-15 04:38 UTC
是否能够在 paddle release 的时候，book 同步 release 一下？

**Comment by jacquesqiao** [comment] 2017-09-15 06:18
现在book的docker每次提交都会更新，而pip版本可能慢一些

**Comment by typhoonzero** [comment] 2017-09-15 06:24
的确需要一种能够保持book的版本和paddle的版本相对应的方法，建议book也做成pip包？然后指定依赖为测试过的paddle的pip包？

**Comment by shanyi15** [comment] 2018-08-15 09:18
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:18 UTC
