### ISSUE TITLE
chapter 07, SRL crashes after it runs a while

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/book#343] opened 2017-07-15 00:30 UTC
Chapter 07, labeling semantic roles, crashes after it runs a while. The error information is as follows. It seems some bug occurs.

```text
B000000087012:Paddle xx$ cd ../book-develop/07.label_semantic_roles/
B000000087012:07.label_semantic_roles xx$ python train.py 
I0714 23:42:26.339615 1946898432 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
I0714 23:42:26.441073 1946898432 GradientMachine.cpp:85] Initing parameters..
I0714 23:42:26.567050 1946898432 GradientMachine.cpp:92] Init parameters done.
Pass 0, Batch 0, Cost 150.801550, {'__sum_evaluator_0__': 1.0}
Error while running 07.label_semantic_roles:  [...Matrix.cpp:2712] Check failed: index[i] < (int)tableSize (39052 vs. 3162) 

Test with Pass 0, Batch 0, {'__sum_evaluator_0__': 0.5385039448738098}
Pass 0, Batch 100, Cost 86.668573, {'__sum_evaluator_0__': 0.4900662302970886}
Pass 0, Batch 200, Cost 82.026624, {'__sum_evaluator_0__': 0.5676567554473877}
Pass 0, Batch 300, Cost 55.416589, {'__sum_evaluator_0__': 0.7542372941970825}
Pass 0, Batch 400, Cost 70.610925, {'__sum_evaluator_0__': 0.7370370626449585}
Pass 0, Batch 500, Cost 85.192023, {'__sum_evaluator_0__': 0.6752411723136902}

Test with Pass 0, {'__sum_evaluator_0__': 0.5385039448738098}
F0714 23:44:25.227174 1946898432 Matrix.cpp:2712] Check failed: index[i] < (int)tableSize (39052 vs. 3162) 
*** Check failure stack trace: ***
    @        0x10925f7ed  google::LogMessage::Flush()
    @        0x109263a6f  google::LogMessageFatal::~LogMessageFatal()
    @        0x1092606a9  google::LogMessageFatal::~LogMessageFatal()
    @        0x10919dfd0  paddle::CpuMatrix::selectRowsImp<>()
    @        0x108f8d263  paddle::MixedLayer::forward()
    @        0x108ff779b  paddle::NeuralNetwork::forward()
    @        0x108f41f94  _wrap_GradientMachine_forward()
    @        0x100fc31bd  PyEval_EvalFrameEx
    @        0x100fc80b2  fast_function
    @        0x100fc2db3  PyEval_EvalFrameEx
    @        0x100fbb8f2  PyEval_EvalCodeEx
    @        0x100fc8015  fast_function
    @        0x100fc2db3  PyEval_EvalFrameEx
    @        0x100f3b7a1  gen_send_ex
    @        0x100fc23b5  PyEval_EvalFrameEx
    @        0x100f3b7a1  gen_send_ex
    @        0x100fc23b5  PyEval_EvalFrameEx
    @        0x100fbb8f2  PyEval_EvalCodeEx
    @        0x100fc8015  fast_function
    @        0x100fc2db3  PyEval_EvalFrameEx
    @        0x100fbb8f2  PyEval_EvalCodeEx
    @        0x100fc8015  fast_function
    @        0x100fc2db3  PyEval_EvalFrameEx
    @        0x100fbb8f2  PyEval_EvalCodeEx
    @        0x100fc8015  fast_function
    @        0x100fc2db3  PyEval_EvalFrameEx
    @        0x100fbb8f2  PyEval_EvalCodeEx
    @        0x100fbb2e6  PyEval_EvalCode
    @        0x100fea254  PyRun_FileExFlags
    @        0x100fe9dd1  PyRun_SimpleFileExFlags
    @        0x100fffa12  Py_Main
Abort trap: 6
```

**Comment by lcy-seso** [comment] 2017-07-15 00:30
I will fix this.

**Comment by hedaoyuan** [comment] 2017-07-25 08:35
@lcy-seso What is the progress of this question, I asked the question is since there are new people encounter this problem. Is this Bug introduced in the latest development process?  @afei-bd will try to run this demo in the previous version.

**Comment by afei-bd** [comment] 2017-07-25 09:19
There exist two versions of paddle book in docker hub: paddlepaddle/book(https://hub.docker.com/r/paddlepaddle/book/tags/) and paddledev/book(https://hub.docker.com/r/paddledev/book/tags/).  The lastest of paddlepaddle/book has the crash problem on chapter 7, while the paddledev/book works fine. I think it would be less confused by merging this two version of  paddle book. Just a suggestion.

**Comment by hedaoyuan** [comment] 2017-07-25 09:35
Thanks @afei-bd.

**Comment by shanyi15** [comment] 2018-08-15 09:16
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:16 UTC
Labels: bug
