### ISSUE TITLE
角色标注例子没有任何标注结果

### ISSUE THREAD

**Issue by jaysharp** [PaddlePaddle/book#452] opened 2017-11-27 05:51 UTC
直接运行docker中的例子，
1.直接运行没有任何标注结果
2.增加训练轮次达到100次，仍然没有任何标注结果
3.改变学习率增加训练轮次，偶尔出现kernel崩溃。

**Comment by shanyi15** [comment] 2018-08-15 09:08
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:08 UTC
