### ISSUE TITLE
ask to translate into indonesian language

### ISSUE THREAD

**Issue by mohdhaekal** [PaddlePaddle/book#485] opened 2018-02-10 04:01 UTC
hello sir ...
 may i translate into indonesia.agar bahasa indonesia is easier to read .....?
 thank you very much for your attention

**Comment by shanyi15** [comment] 2018-02-26 11:12
Thank you for your suggestion.
We're happy to seeing indonesia version of documentation.
However, we're sorry that the used language of paddlepaddle.org (including book) is English and Chinese.
Therefore, we encourage developers to create a developer community and the indonesia version of book  can be put here.

**Comment by shanyi15** [comment] 2018-08-15 09:15
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:15 UTC
