### ISSUE TITLE
Numeric prefix of chapters don't exist in Docker images

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/book#340] opened 2017-07-10 00:23 UTC
I ran the Docker images 

```bash
docker run -p 8888:8888 paddlepaddle/book
```

and got the following content in my Web browser:

![screen shot 2017-07-09 at 5 18 53 pm](https://user-images.githubusercontent.com/1548775/27998914-1c1d6de0-64cb-11e7-9c70-9655d9e9cc77.png)

We see that the directory prefixes like `00.`, `01.` etc do not exist in the Docker image.

These prefixes are important because they direct Jupyter Notebook to sort directories in the order of book chapters.

**Comment by wangkuiyi** [comment] 2017-07-10 00:34
I tried to get into the running book container and confirmed that the directories in `/book` do not have numeric prefixes.

```
$ docker exec -i -t festive_gates /bin/bash
root@e40a99ceab09:/# ls /book
fit_a_line	      image_qa		  index.html.json	pre-commit-hooks    recommender_system	understand_sentiment
gan		      index.en.html	  index.html.tmpl	query_relationship  skip_thought	word2vec
image_caption	      index.en.html.json  label_semantic_roles	README.en.md	    speech_recognition
image_classification  index.en.html.tmpl  machine_translation	README.md	    tools
image_detection       index.html	  paddle		recognize_digits    travis
```

**Comment by wangkuiyi** [comment] 2017-07-10 00:36
I browsed the script that builds the Docker image.  It seems that it runs a COPY directive at https://github.com/PaddlePaddle/book/blob/develop/.tools/build_docker.sh#L50.  But I am not sure what is the `.` (current directory) would be when we run this script.  I am also not sure who would run above script.

**Comment by typhoonzero** [comment] 2017-07-10 01:54
Seems that we didn't build and push the latest book image to dockerhub.

**Comment by gangliao** [comment] 2017-07-10 02:15
@wangkuiyi  build_docker.sh will be executed by TeamCity. I am curious which version of `Book` you use here.

**Comment by wangkuiyi** [comment] 2017-07-10 05:09
@gangliao   It is weird!

```
root@e40a99ceab09:/# paddle version
PaddlePaddle 0.9.0a0, compiled with
    with_avx: ON
    with_gpu: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_metric_learning: 
    with_timer: OFF
    with_predict_sdk: 
```

**Comment by wangkuiyi** [comment] 2017-07-10 05:10
It seems that we should push the most recent version with tag `lastest`, as @typhoonzero said.

**Comment by gangliao** [comment] 2017-07-10 05:15
yeah, we already did this. I need to log in the TeamCity server to observe what happened here, but this server hangs/freezes now.

**Comment by wangkuiyi** [comment] 2017-07-10 05:17
I see. Thanks @gangliao @typhoonzero .  I hope @helinwang could be in the office tomorrow and can fix TeamCity.

**Comment by helinwang** [comment] 2017-07-11 18:30
@gangliao @wangkuiyi Thanks! TeamCity is fixed.

**Comment by shanyi15** [comment] 2018-08-15 09:09
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:09 UTC
