### ISSUE TITLE
06understand_sentiment, 直接运行报错'generator' object is not callable 

### ISSUE THREAD

**Issue by Archimondecy** [PaddlePaddle/book#480] opened 2018-01-24 11:56 UTC
运行02识别数字没问题，06报错。
如下文报错：TypeError: 'generator' object is not callable

I0124 19:52:20.866607 24031 Util.cpp:166] commandline:  --use_gpu=False 
W0124 19:52:20.866672 24031 CpuId.h:112] PaddlePaddle wasn't compiled to use avx instructions, but these are available on your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON
load dictionary...
I0124 19:53:14.328279 24031 GradientMachine.cpp:85] Initing parameters..
I0124 19:53:14.465420 24031 GradientMachine.cpp:92] Init parameters done.
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    num_passes=20)
  File "/home/map/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/v2/trainer.py", line 154, in train
    for batch_id, data_batch in enumerate(reader()):
  File "/home/map/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/v2/minibatch.py", line 33, in batch_reader
    for instance in r:
  File "/home/map/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 67, in data_reader
    for e in reader():
TypeError: 'generator' object is not callable

**Comment by shanyi15** [comment] 2018-08-15 09:07
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:08 UTC
