### ISSUE TITLE
求解 新手入门---线性回归中的部分 疑惑

### ISSUE THREAD

**Issue by wwlaoxi** [PaddlePaddle/book#367] opened 2017-08-31 15:35 UTC
1、怎么样查看uci_housing的数据？
2、打印相关信息
  # event_handler to print training and testing info
  def event_handler(event):
    if isinstance(event, paddle.event.EndIteration):
        if event.batch_id % 100 == 0:
            print "Pass %d, Batch %d, Cost %f" % (
                event.pass_id, event.batch_id, event.cost)

    if isinstance(event, paddle.event.EndPass):
        result = trainer.test(
            reader=paddle.batch(
                uci_housing.test(), batch_size=2),
            feeding=feeding)
        print "Test %d, Cost %f" % (event.pass_id, result.cost)

打印出来的结果如下
Pass 0, Batch 0, Cost 5.598552
Pass 0, Batch 100, Cost 32.202789
Pass 0, Batch 200, Cost 87.088058
Test 0, Cost 13.278372
Pass 1, Batch 0, Cost 78.872978
Pass 1, Batch 100, Cost 424.313202
Pass 1, Batch 200, Cost 12.719980
Test 1, Cost 13.332345
关于那个print "Test %d, Cost %f" % (event.pass_id, result.cost)
代表result.cost 是一个batch的cost，还是说uci_housing.test()所有的cost啊？

**Comment by QiJune** [comment] 2017-09-05 01:58
1 uci_housing的数据可以自己写python代码读取
```
test_data_creator = paddle.dataset.uci_housing.test()
    test_data = []
    test_label = []

    for item in test_data_creator():
        test_data.append((item[0], ))
        test_label.append(item[1])
        if len(test_data) == 5:
            break
```
这里就可以打印每一个data 和 label

2 这里的cost是所有以训练数据的cost；当训练完成的时候，会对测试数据进行测试，得到测试数据的cost

**Comment by shanyi15** [comment] 2018-08-15 09:15
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:15 UTC
