### ISSUE TITLE
08.recommender_system/train.py falied with GPU

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/book#307] opened 2017-04-27 06:54 UTC
I0427 06:52:26.296445   134 Util.cpp:161] commandline:  --use_gpu=True
[INFO 2017-04-27 06:52:28,615 networks.py:1472] The input order is [user_id, gender_id, age_id, job_id, movie_id, category_id, movie_title, score]
[INFO 2017-04-27 06:52:28,615 networks.py:1478] The output order is [__mse_cost_0__]
[INFO 2017-04-27 06:52:28,624 networks.py:1472] The input order is [user_id, gender_id, age_id, job_id, movie_id, category_id, movie_title, score]
[INFO 2017-04-27 06:52:28,624 networks.py:1478] The output order is [__mse_cost_0__]
I0427 06:52:28.631453   134 GradientMachine.cpp:86] Initing parameters..
I0427 06:52:28.666503   134 GradientMachine.cpp:93] Init parameters done.
F0427 06:52:28.772764   134 Matrix.cpp:645] Not supported
*** Check failure stack trace: ***
    @     0x7f16927a937d  google::LogMessage::Fail()
    @     0x7f16927acec5  google::LogMessage::SendToLog()
    @     0x7f16927a8ea3  google::LogMessage::Flush()
    @     0x7f16927ae3de  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f16925c0706  paddle::GpuMatrix::mul()
    @     0x7f16924a7b1c  paddle::FullyConnectedLayer::forward()
    @     0x7f1692431664  paddle::NeuralNetwork::forward()
    @     0x7f169241eb23  paddle::GradientMachine::forwardBackward()
    @     0x7f1692786617  GradientMachine::forwardBackward()
    @     0x7f16923e5e47  _wrap_GradientMachine_forwardBackward
    @           0x52714b  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x525560  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x524338  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x524338  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x525560  PyEval_EvalFrameEx
    @           0x567d14  (unknown)
    @           0x465bf4  PyRun_FileExFlags
    @           0x46612d  PyRun_SimpleFileExFlags
    @           0x466d92  Py_Main
    @     0x7f169557cf45  __libc_start_main
    @           0x577c2e  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by TexasRangers86** [comment] 2017-10-13 03:33
Hey, I got this error. When I set `paddle.init(use_gpu=True, trainer_count=2)` ,  deal this problem;
But when I set trainer_count to 1 or 3 or 4, also got this error;

**Comment by QiJune** [comment] 2017-10-13 03:47
Paddle does not support sparse matrix multiply with a dense matrix in GPU now. In recommender system demo, we have a sparse input data. So, it will cause error in FullyConnectedLayer(Multiply).

**Comment by shanyi15** [comment] 2018-08-15 09:09
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:09 UTC
