### ISSUE TITLE
rnn text generation exception

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/book#420] opened 2017-09-20 20:41 UTC
from @Tony Fu

```
[INFO 2017-09-17 14:19:12,094 beam_search.py:38] dictionay len = 51200
F0917 14:20:00.483598    18 Allocator.h:54] Check failed: posix_memalign(&ptr, 4096ul, size) == 0 (12 vs. 0) 
*** Check failure stack trace: ***
    @     0x7face3d9a11d  google::LogMessage::Fail()
    @     0x7face3d9c468  google::LogMessage::SendToLog()
    @     0x7face3d99c0b  google::LogMessage::Flush()
    @     0x7face3d9d33e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7face3b995e1  paddle::CpuAllocator::alloc()
    @     0x7face3b85f18  paddle::PoolAllocator::alloc()
    @     0x7face3b859c5  paddle::CpuMemoryHandle::CpuMemoryHandle()
    @     0x7face3b5a7f3  paddle::CpuMatrix::CpuMatrix()
    @     0x7face3b5a97e  paddle::Matrix::create()
    @     0x7face3b6d798  paddle::Matrix::resizeOrCreate()
    @     0x7face3956187  paddle::LstmLayer::forward()
    @     0x7face3a35279  paddle::NeuralNetwork::forward()
    @     0x7face3853b26  _wrap_GradientMachine_forward
    @           0x4c468a  PyEval_EvalFrameEx
    @           0x4c9d8f  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca8d1  PyEval_EvalFrameEx
    @           0x4dddca  (unknown)
    @           0x4c4c6f  PyEval_EvalFrameEx
    @           0x4dddca  (unknown)
    @           0x4c4c6f  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca099  PyEval_EvalFrameEx
    @           0x4c9d8f  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca8d1  PyEval_EvalFrameEx
    @           0x4c9d8f  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4c2509  PyEval_EvalCode
    @           0x4f1def  (unknown)
    @           0x4ec652  PyRun_FileExFlags
    @           0x4eae31  PyRun_SimpleFileExFlags
Aborte
```

**Comment by jacquesqiao** [comment] 2017-09-20 20:41
The system memory is not enough.

**Comment by shanyi15** [comment] 2018-08-15 09:18
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:18 UTC
Labels: HackMIT
