### ISSUE TITLE
[ 06.understand_sentiment ][README.cn.ipynb] infer:Duplicated layer name: word

### ISSUE THREAD

**Issue by livc** [PaddlePaddle/book#336] opened 2017-07-05 11:24 UTC
I'm updating our RegressionTest code, and I got an error when running the .py file which is converted from .ipynb file:

```bash
$ jupyter nbconvert --to python README.cn.ipynb
$ python README.cn.py

……
……
[CRITICAL 2017-07-05 11:14:25,124 layers.py:854] Duplicated layer name: word
Traceback (most recent call last):
  File "tmp.py", line 427, in <module>
    out = convolution_net(dict_dim, class_dim=class_dim, is_predict=True)
  File "tmp.py", line 137, in convolution_net
    paddle.data_type.integer_value_sequence(input_dim))
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/layer.py", line 88, in __data_layer__
    l = v1_layers.data_layer(name, type.dim, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 350, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 854, in data_layer
    **ExtraLayerAttribute.to_kwargs(layer_attr))
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3136, in Layer
    return layer_func(name, **xargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 1681, in __init__
    name, 'data', size, inputs=[], device=device)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 1363, in __init__
    'Duplicated layer name: %s' % name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 156, in config_assert
    logger.fatal(msg)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3482, in my_fatal
    raise Exception()
Exception
```

**Comment by lcy-seso** [comment] 2017-07-07 10:30
hi~ this is a known error. I will look into this.

**Comment by cszhou** [comment] 2017-08-13 16:11
又踩到这个坑来了。。这个bug还没修复么。。

**Comment by hxs91** [comment] 2018-01-23 10:53
同踩到这个坑了……

**Comment by shanyi15** [comment] 2018-08-15 09:09
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:09 UTC
Labels: bug
