### ISSUE TITLE
图像自动生成

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/book#11] opened 2016-12-16 10:04 UTC
请先阅读[中文教程撰写统一标准](https://github.com/PaddlePaddle/book/wiki/中文教程撰写统一标准)。

要求：
- 时间节点：2016.12.26前提交临时版，2017.01.03前提交完整的第一版，2017.01.15前全部完成。
- 提交地址：[gan目录](https://github.com/PaddlePaddle/book/blob/develop/gan/)。
- 已有参考：[demo代码](https://github.com/PaddlePaddle/Paddle/tree/develop/demo/gan)。

**Comment by shanyi15** [comment] 2018-08-15 09:18
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:18 UTC
