### ISSUE TITLE
第6课understand sentiment的doc示例代码目录结构和源码目录结构不一致

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/book#454] opened 2017-11-28 08:59 UTC
[github源码](https://github.com/PaddlePaddle/book/tree/develop/06.understand_sentiment)的目录结构如：
![image](https://user-images.githubusercontent.com/3206718/33310680-5ea3df1c-d45d-11e7-87a9-a208e0a85897.png)

[doc](http://www.paddlepaddle.org/docs/develop/models/text_classification/README.html)中的目录结构如：
![image](https://user-images.githubusercontent.com/3206718/33310764-a9cdf09a-d45d-11e7-8228-6a27185b21c5.png)

**Comment by OleNet** [comment] 2017-11-28 09:02
doc中，点击情感分类，会链到github中的上图

**Comment by shanyi15** [comment] 2018-08-15 09:08
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:08 UTC
