### ISSUE TITLE
求解 识别数字中的 疑惑 

### ISSUE THREAD

**Issue by wwlaoxi** [PaddlePaddle/book#369] opened 2017-09-01 16:16 UTC
1、卷积神经网络LeNet-5 中 convolutional_neural_network 函数中没有设置卷积时滤波器（卷积核）的滑动步长，该滑动步长默认是多少？如果设置的话需要设置哪个参数，怎么设置？
2、训练方法（optimizer)的L2正规化是针对所有的参数都正规化吗？
3、使用训练好的模型对手写体数字图片进行分类，报错，其中代码如下：
  test_data = []
cur_dir = os.path.dirname(os.path.realpath(__file__))
test_data.append((load_image(cur_dir + '/image/infer_3.png'),))
错误如下：
NameErrorTraceback (most recent call last)
<ipython-input-19-108631bb6626> in <module>()
     10 
     11 test_data = []
---> 12 cur_dir = os.path.dirname(os.path.realpath(__file__))
     13 test_data.append((load_image(cur_dir + '/image/infer_3.png'),))
     14 #test_data.append((load_image('/image/infer_3.png'),))

NameError: name '__file__' is not defined

**Comment by yeyupiaoling** [comment] 2017-10-24 13:22
这代码是你写的吗，怎么跟官网的不一样

**Comment by shanyi15** [comment] 2018-08-15 09:18
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:18 UTC
