### ISSUE TITLE
请教关于训练数据的归一化问题

### ISSUE THREAD

**Issue by cdliheng** [PaddlePaddle/book#486] opened 2018-02-16 12:06 UTC
官方自带的“基本使用概念”里面有个线性回归的例子，使用的训练数据集是自己传入的。
我把数据值修改大了，比如[5061,245]，就会报“The kernel appears to have died. It will restart automatically.”错误。请问该如何解决呢？谢谢。
附上代码：

define training dataset reader
def train_reader():
train_x = np.array([[1, 1], [1, 2], [3, 4], [5, 2]])
train_y = np.array([[-2], [-3], [-7], [-7]])

def reader():
    for i in xrange(train_y.shape[0]):
        yield train_x[i], train_y[i]

return reader

**Comment by shanyi15** [comment] 2018-08-15 09:15
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:15 UTC
