### ISSUE TITLE
book/04.word2vec/的demo程序出错

### ISSUE THREAD

**Issue by iamadog3333** [PaddlePaddle/book#495] opened 2018-03-11 10:38 UTC
I0311 18:32:50.721074 3406201792 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=3 
I0311 18:32:51.937851 3406201792 GradientMachine.cpp:85] Initing parameters..
I0311 18:32:51.954010 3406201792 GradientMachine.cpp:92] Init parameters done.
Thread [0x70000f129000] Forwarding __fc_layer_0__, 
*** Aborted at 1520764372 (unix time) try "date -d @1520764372" if you are using GNU date ***

PC: @                0x0 (unknown)

*** SIGBUS (@0x70000f0a88f0) received by PID 26709 (TID 0x70000f129000) stack trace: ***

    @     0x7fffc2363b3a _sigtramp

    @        0x110841d91 sgemm_thread_nn

    @        0x11072a247 cblas_sgemm

    @        0x1106562d5 paddle::gemm<>()

    @        0x1106688ba paddle::CpuMatrix::mul()

    @        0x110454a6e paddle::FullyConnectedLayer::forward()

    @        0x1104a674e paddle::NeuralNetwork::forward()

    @        0x1104b1a14 paddle::TrainerThread::forward()

    @        0x1104b1780 paddle::TrainerThread::computeThread()

    @        0x1104b5230 _ZNSt3__114__thread_proxyINS_5tupleIJZN6paddle13TrainerThread5startEvE3$_1EEEEEPvS6_

    @     0x7fffc236d93b _pthread_body

    @     0x7fffc236d887 _pthread_start
[Finished in 2.9s]

**Comment by iamadog3333** [comment] 2018-03-11 10:42
paddlepaddle (0.10.0)  版本环境。

**Comment by iamadog3333** [comment] 2018-03-12 03:40
run at ipython notebook is ok.
but fail at python paddlepaddle (0.10.0)

**Comment by shanyi15** [comment] 2018-08-15 09:15
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:15 UTC
