### ISSUE TITLE
官网paddlepaddle/book:latest在运行07.label_semantic_roles和paddlepaddle/book:0.10.0在运行08.machine_translation有点小问题

### ISSUE THREAD

**Issue by chengduoZH** [PaddlePaddle/book#356] opened 2017-08-01 04:57 UTC
在paddlepaddle/book:0.10.0中运行08.machine_translation会出现如下问题：
```
root@2326a7bdee57:/book/08.machine_translation# python train.py
I0801 03:01:01.564342    15 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1
[INFO 2017-08-01 03:01:01,658 networks.py:1482] The input order is [source_language_word, target_language_word, target_language_next_word]
[INFO 2017-08-01 03:01:01,659 networks.py:1488] The output order is [__classification_cost_0__]
[INFO 2017-08-01 03:01:01,692 networks.py:1482] The input order is [source_language_word, target_language_word, target_language_next_word]
[INFO 2017-08-01 03:01:01,692 networks.py:1488] The output order is [__classification_cost_0__]
I0801 03:01:02.328541    15 GradientMachine.cpp:86] Initing parameters..
I0801 03:01:05.297921    15 GradientMachine.cpp:93] Init parameters done.

Pass 0, Batch 0, Cost 195.874988, {'classification_error_evaluator': 1.0}
.........
Pass 0, Batch 10, Cost 204.007812, {'classification_error_evaluator': 0.9292929172515869}
.........
Pass 0, Batch 20, Cost 257.487524, {'classification_error_evaluator': 0.9279999732971191}
.........
Pass 0, Batch 30, Cost 300.606274, {'classification_error_evaluator': 0.9041095972061157}
.........
Pass 0, Batch 40, Cost 216.137231, {'classification_error_evaluator': 0.9523809552192688}
.......*** Aborted at 1501556672 (unix time) try "date -d @1501556672" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7fc30ddebe86) received by PID 15 (TID 0x7fc305d14700) from PID 232701574; stack trace: ***
    @     0x7fc30f0c0330 (unknown)
    @     0x7fc30ddebe86 paddle::AssignCpuEvaluate<>()
    @     0x7fc30dded0ac paddle::AssignEvaluate<>()
    @     0x7fc30dde7d5b paddle::adamApply()
    @     0x7fc30dde54a6 paddle::AdamParameterOptimizer::update()
    @     0x7fc30ddcfc17 paddle::SgdThreadUpdater::threadUpdateDense()
    @     0x7fc30ddd0d9f _ZNSt17_Function_handlerIFvimEZN6paddle16SgdThreadUpdater11finishBatchEfEUlimE_E9_M_invokeERKSt9_Any_dataim
    @     0x7fc30c7554ec _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle14SyncThreadPool5startEvEUliE_mEEE6_M_runEv
    @     0x7fc30b715a60 (unknown)
    @     0x7fc30f0b8184 start_thread
    @     0x7fc30ede5bed clone
    @                0x0 (unknown)
Floating point exception
```

 
在paddlepaddle/book:latest中运行07.label_semantic_roles会出现如下问题：
```
root@209789cb8eed:/book/07.label_semantic_roles# python train.py
I0801 04:40:38.478021   139 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1
I0801 04:40:38.577181   139 GradientMachine.cpp:85] Initing parameters..
I0801 04:40:38.765612   139 GradientMachine.cpp:92] Init parameters done.
Pass 0, Batch 0, Cost 121.618921, {'__sum_evaluator_0__': 1.0}

Test with Pass 0, Batch 0, {'__sum_evaluator_0__': 0.5385039448738098}
Pass 0, Batch 100, Cost 61.798883, {'__sum_evaluator_0__': 0.6978852152824402}
Pass 0, Batch 200, Cost 68.420306, {'__sum_evaluator_0__': 0.5071942210197449}
Pass 0, Batch 300, Cost 89.819623, {'__sum_evaluator_0__': 0.8310810923576355}
Pass 0, Batch 400, Cost 75.320734, {'__sum_evaluator_0__': 0.5387097001075745}
Pass 0, Batch 500, Cost 60.577905, {'__sum_evaluator_0__': 0.748275876045227}

Test with Pass 0, {'__sum_evaluator_0__': 0.7465202808380127}
F0801 04:42:45.812535   139 Matrix.cpp:2540] Check failed: index[i] < (int)tableSize (39052 vs. 3162)
*** Check failure stack trace: ***
    @     0x7fa82a2bc78d  google::LogMessage::Fail()
    @     0x7fa82a2bead8  google::LogMessage::SendToLog()
    @     0x7fa82a2bc27b  google::LogMessage::Flush()
    @     0x7fa82a2bf9ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa82a1e3dbd  paddle::CpuMatrix::selectRowsImp<>()
    @     0x7fa82a1e12be  paddle::CpuMatrix::selectRows()
    @     0x7fa829ee41a9  paddle::TableProjection::forward()
    @     0x7fa829f4ba14  paddle::MixedLayer::forward()
    @     0x7fa82a025fd1  paddle::NeuralNetwork::forward()
    @     0x7fa829e8a1c6  _wrap_GradientMachine_forward
    @           0x4c468a  PyEval_EvalFrameEx
    @           0x4c9d8f  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca8d1  PyEval_EvalFrameEx
    @           0x4dddca  (unknown)
    @           0x4c4c6f  PyEval_EvalFrameEx
    @           0x4dddca  (unknown)
    @           0x4c4c6f  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca099  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca099  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca8d1  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4c2509  PyEval_EvalCode
    @           0x4f1def  (unknown)
    @           0x4ec652  PyRun_FileExFlags
    @           0x4eae31  PyRun_SimpleFileExFlags
    @           0x49e14a  Py_Main
    @     0x7fa840e1b830  __libc_start_main
    @           0x49d9d9  _start
Aborted
```

**Comment by gangliao** [comment] 2017-08-01 05:59
08.machine_translation 应该已经解决了  07.label_semantic_roles这个问题 需要请算法的同学专门跟一下 fix一下

**Comment by gangliao** [comment] 2017-08-01 06:03
@chengduoZH  07这一章你用的是`root@209789cb8eed:/book/07.label_semantic_roles# python train.py`, 有在notebook里面跑过吗？ notebook的ipynb文件可能和train.py不完全一致

**Comment by chengduoZH** [comment] 2017-08-01 06:49
@gangliao notebook里面也是问题

**Comment by shanyi15** [comment] 2018-08-15 09:16
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:16 UTC
Labels: bug
