### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by fkuner** [PaddlePaddle/book#560] opened 2018-06-29 04:04 UTC
<Figure size 600x400 with 0 Axes>
Traceback (most recent call last):

  File "<ipython-input-3-ceb20fca6c67>", line 1, in <module>
    runfile('/home/sleep/Recognize Digits.py', wdir='/home/sleep')

  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)

  File "/home/sleep/Recognize Digits.py", line 132, in <module>
    best = sorted(lists, key=lambda list: float(list[1]))[0]
IndexError: list index out of range

what happened?

**Comment by typhoonzero** [comment] 2018-06-29 04:36
Sorry, can you provide the steps to reproduce this error so that I can try to figure out where this error might be?

**Comment by shanyi15** [comment] 2018-08-15 09:02
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:02 UTC
