### ISSUE TITLE
paddlepaddle-gpu可以在Windows下 pip安装吗？

### ISSUE THREAD

**Issue by breaknormal1** [PaddlePaddle/book#456] opened 2017-12-05 02:25 UTC
paddlepaddle-gpu可以在Windows下 pip安装吗？
可以这样用吗？
Ubuntu下好难搞啊，NVIDIA驱动一直没搞定

**Comment by NHZlX** [comment] 2017-12-05 02:42
目前不支持windows的pip安装， 如果ubuntu 源码安装，可以参考http://www.jianshu.com/p/c6264cd5f5c7

**Comment by shanyi15** [comment] 2018-08-15 09:08
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:08 UTC
