### ISSUE TITLE
06.label_semantic_roles/train.py 用GPU运行时报错

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/book#281] opened 2017-04-16 10:24 UTC
修改了train.py中的use_gpu=False > True，运行python train.py 打印错误信息如下：

> python train.py 
I0416 10:17:39.718773   830 Util.cpp:161] commandline:  --use_gpu=True --trainer_count=1 
[WARNING 2017-04-16 10:17:40,129 networks.py:1444] `outputs` routine try to calculate network's inputs and outputs order. It might not work well.Please see follow log carefully.
[INFO 2017-04-16 10:17:40,137 networks.py:1472] The input order is [word_data, ctx_n2_data, ctx_n1_data, ctx_0_data, ctx_p1_data, ctx_p2_data, verb_data, mark_data, target]
[INFO 2017-04-16 10:17:40,137 networks.py:1478] The output order is [__crf_layer_0__, crf_dec_l]
[INFO 2017-04-16 10:17:40,171 networks.py:1472] The input order is [word_data, ctx_n2_data, ctx_n1_data, ctx_0_data, ctx_p1_data, ctx_p2_data, verb_data, mark_data, target]
[INFO 2017-04-16 10:17:40,171 networks.py:1478] The output order is [__crf_layer_0__]
I0416 10:17:40.196336   830 GradientMachine.cpp:86] Initing parameters..
I0416 10:17:40.396483   830 GradientMachine.cpp:93] Init parameters done.
F0416 10:17:42.085708   830 CRFLayer.cpp:57] Check failed: !useGpu_ GPU is not supported
*** Check failure stack trace: ***
    @     0x7f44c87db37d  google::LogMessage::Fail()
    @     0x7f44c87deec5  google::LogMessage::SendToLog()
    @     0x7f44c87daea3  google::LogMessage::Flush()
    @     0x7f44c87e03de  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f44c850ff01  paddle::CRFLayer::forward()
    @     0x7f44c8463664  paddle::NeuralNetwork::forward()
    @     0x7f44c8450b23  paddle::GradientMachine::forwardBackward()
    @     0x7f44c87b8617  GradientMachine::forwardBackward()
    @     0x7f44c8417e47  _wrap_GradientMachine_forwardBackward
    @           0x52714b  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x525560  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x524338  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x524338  PyEval_EvalFrameEx
    @           0x5247ea  PyEval_EvalFrameEx
    @           0x567d14  (unknown)
    @           0x465bf4  PyRun_FileExFlags
    @           0x46612d  PyRun_SimpleFileExFlags
    @           0x466d92  Py_Main
    @     0x7f44cdbe4f45  __libc_start_main
    @           0x577c2e  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

train.py 改回use_gpu= True > False 错误信息消失，其他simple用类似方式修改为gpu下运行没有出现这个问题。

**Comment by QiJune** [comment] 2017-04-17 03:50
这个问题是paddle的CRF Layer目前还不支持GPU，仅可以在CPU上运行

**Comment by lcy-seso** [comment] 2017-05-03 10:40
CRF 不适合在 GPU上实现，我们应该以 SRL 为例提供一个能让某个/某些层在 CPU 上跑，其余层在 GPU上跑的例子。

**Comment by lcy-seso** [comment] 2017-05-03 10:45
Currently, LinearChainCRF in PaddlePaddle is not friendly to GPU implementation, and we are not planning to provide a GPU implementation of linear chain CRF, but PaddlePaddle allows a certain layer or some layers runs in CPU while the rest running in GPU.

I think we should use SRL as an example to show **how to train a model by using CPU and GPU**.

**Comment by shanyi15** [comment] 2018-08-15 09:09
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:09 UTC
Labels: enhancement, question
