### ISSUE TITLE
这才是Tutorial

### ISSUE THREAD

**Issue by Zrachel** [PaddlePaddle/book#34] opened 2017-01-06 11:13 UTC
只是一个例子，感觉写得很好，和大家分享一下。

比如说写LSTM，https://deeplearning4j.org/lstm

![image](https://cloud.githubusercontent.com/assets/4532062/21716095/4636bd16-d443-11e6-8bc3-f3d2b841d9c3.png)

需要几个点：RNN和feedforword network的关联，BP的改进——BPTT，简单RNN为什么走不下去了——梯度消失和梯度爆炸问题， LSTM怎样解决的该问题，长时序传播问题。

再比如CNN，https://deeplearning4j.org/convolutionalnets 讲得也非常到位

另外，大家还可以参考左边栏的目录，参考其他章节的知识和结构，共同完善我们的tutorial。

**Comment by lcy-seso** [comment] 2017-01-19 06:40
这些些的很好的教程里面都讲了很多“为什么”，而不仅仅是“怎么做”，这是我们现在比较缺的。

**Comment by yu239-zz** [comment] 2017-01-24 02:14
I have several suggestions about the tutorial. I feel the same thing with @lcy-seso after reading the paddlepaddle book. Most of the paragraphs are about what to do like following instructions to solve a problem. For people who really want to learn deep learning, I think more explanations about why we should do that and the math or intuition behind are needed. Each chapter should convey the ideas from shallow to deep, without listing too many references or terminology in the first place. Otherwise the readers will easily get lost while reading. @cxwangyi

**Comment by shanyi15** [comment] 2018-08-15 09:16
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:16 UTC
