### ISSUE TITLE
请问The kernel appears to have died. It will restart automatically.是什么原因？

### ISSUE THREAD

**Issue by Vcdan** [PaddlePaddle/book#460] opened 2017-12-10 12:56 UTC
在Jupyter Notebook中运行fit_a_line里的代码时，显示：“The kernel appears to have died. It will restart automatically.”
Git Bash中如下：
![image](https://user-images.githubusercontent.com/33109831/33805014-1c6aec10-ddec-11e7-9240-91105f7bf361.png)
请问这是什么原因？

**Comment by tigerneil** [comment] 2017-12-11 03:50
It seems like you are running out of memory. so give your docker machine more memory to see what happen.
![image](https://user-images.githubusercontent.com/5799436/33815036-629aee6a-de69-11e7-81fa-0924bea0e26f.png) I use this setting.

**Comment by shanyi15** [comment] 2018-08-15 09:08
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:08 UTC
