### ISSUE TITLE
capi正式化后的置信度获取

### ISSUE THREAD

**Issue by fmantianxing** [PaddlePaddle/book#551] opened 2018-06-20 07:35 UTC
线下预测获取的每条prob的大小prob_size==beam_size，模型类似于：https://github.com/PaddlePaddle/book/tree/develop/08.machine_translation

但是，使用capi正式化时使用如下方法得到的prob_size!=beam_size，貌似等于输出序列长度+beam_size，获取代码如下：
￼
![image](https://user-images.githubusercontent.com/6702524/41643910-347b6394-749f-11e8-99fb-2e59677aaafb.png)

请问这是什么原因？我该怎么预测序列的概率？

**Comment by JiayiFeng** [comment] 2018-06-20 15:54
该问题已经线下沟通

**Comment by shanyi15** [comment] 2018-08-15 09:06
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:06 UTC
