### ISSUE TITLE
some problems to do of book docker image

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/book#231] opened 2017-03-20 11:14 UTC
1.  If we try it for two or more times, kernel will die because google log can't be inited repeatedly
```python
paddle.init(use_gpu=False, trainer_count=1)
```

2. Do we need move index.html.tmpl and index.html.json to other directory?Because user need not to know these files？

3. We need a script to check ipynb files quickly。@gongweibao

4. Do we need to rm Chinese documents, and keep only English documents?

5. Modify travis to auto build and push book docker image @gongweibao

6. Machine_translation reports error after running some batchs @jacquesqiao 
#234

**Comment by llxxxll** [comment] 2017-03-20 14:32
2.index.html.json 、index.html.tmpl 可以过滤掉。

**Comment by llxxxll** [comment] 2017-03-20 14:51
fit_a_line/创建参数&创建Trainer 这两部分对应的代码运行起来会报错。
`
[INFO 2017-03-20 14:36:07,782 networks.py:1472] The input order is [x, y]
[INFO 2017-03-20 14:36:07,786 networks.py:1478] The output order is [__mse_cost_0__]
`
但是对最后的『开始训练』没有影响，是不是应该跟某一块代码合并到一起？

**Comment by llxxxll** [comment] 2017-03-20 15:00
是否需要增加一个退出NotebookApp的提示。
方便用户在命令行重现的时候，可以更方便的直接运行`.py`，重现生产环境下的训练过程。

**Comment by wangkuiyi** [comment] 2017-03-20 15:03
> Do we need move index.html.tmpl and index.html.json to other directory?Because user need not to know these files？

Highly support!  It seems that we should move `.tmpl` and `.scheme` to `.tools`. I can try file a PR for your review.

**Comment by gongweibao** [comment] 2017-03-20 15:58
>[INFO 2017-03-20 14:36:07,782 networks.py:1472] The input order is [x, y] [INFO 2017-03-20 14:36:07,786 networks.py:1478] The output order is [__mse_cost_0__]

这是INFO不是error
@llxxxll

**Comment by shanyi15** [comment] 2018-08-15 09:10
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:10 UTC
