### ISSUE TITLE
capi v2 设置多线程，结果只调用了一个processor

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/book#512] opened 2018-04-18 02:37 UTC
![2018-04-18 10 36 01](https://user-images.githubusercontent.com/22136543/38908752-56c1355a-42f4-11e8-81d0-e3b69a51dc41.png)
问题如图，设置了16个thread，速度比单线程还慢，发现只用了一个processor。

**Comment by dzhwinter** [comment] 2018-04-18 02:50
请问用的是哪个inference library呢

**Comment by hyo009** [comment] 2018-04-18 02:56
http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/capi/compile_paddle_lib_cn.html

![2018-04-18 10 55 16](https://user-images.githubusercontent.com/22136543/38909404-15434160-42f7-11e8-87cd-dabf2aed671c.png)

按照这方式编译的动态库

**Comment by dzhwinter** [comment] 2018-04-18 04:42
请问是怎么设置线程的，是设置trainer_count=16了吗？可以参考https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/dense/mnist_v2.py

**Comment by shanyi15** [comment] 2018-08-15 09:07
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:07 UTC
Labels: usr
